development:
  site_name: <Site Name Goes Here>
  per_page: <Paginate Per Page>
  mail_from: no-reply@site-name.com

test:
  site_name: <Site Name Goes Here>
  per_page: <Paginate Per Page>
  mail_from: no-reply@site-name.com

produuction:
  site_name: <Site Name Goes Here>
  per_page: <Paginate Per Page>
  mail_from: no-reply@site-name.com
